name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test-cover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gcovr

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Debug \
                -DHFT_BUILD_TESTS=ON \
                -DHFT_ENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build build

      - name: Run unit tests
        run: ctest --output-on-failure --test-dir build

      - name: Generate coverage report
        run: cmake --build build --target coverage

      - name: Publish coverage summary
        if: always()
        run: |
          if [ -f build/coverage/summary.txt ]; then
            echo '### Coverage Summary' >> "$GITHUB_STEP_SUMMARY"
            cat build/coverage/summary.txt >> "$GITHUB_STEP_SUMMARY"
          else
            echo 'Coverage summary not found' >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage/
          if-no-files-found: warn
